---
Resources:
  SpaBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private

  APIGatewayAWSProxyExecRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ${self:service}-${opt:stage}-${opt:region}-spa-s3-proxy
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: ${self:service}-${opt:stage}-spa-bucket-access
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - 's3:Get*'
                  - 's3:List*'
                Resource:
                  - Fn::GetAtt: [ SpaBucket, Arn ]
                  - Fn::Join:
                      - '/'
                      - - Fn::GetAtt: [ SpaBucket, Arn ]
                        - '*'

  SpaServer:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: ${self:service}-${opt:stage}
      MinimumCompressionSize: 0
      EndpointConfiguration:
        Types:
          - REGIONAL
        VpcEndpointIds:
          - ${self:custom.apig.vpcEndpointId, 'undefined'}
      Policy:
        Statement:
          - Effect: Allow
            Principal: '*'
            Action: execute-api:Invoke
            Resource:
              - execute-api:/*/*/*
      BinaryMediaTypes:
        - '*/*'

  SpaServerResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId:
        Fn::GetAtt: [ SpaServer, RootResourceId ]
      RestApiId:
        Ref: SpaServer
      PathPart: '{proxy+}'

  SpaServerRootMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: GET
      ResourceId:
        Fn::GetAtt: [ SpaServer, RootResourceId ]
      RestApiId:
        Ref: SpaServer
      AuthorizationType: NONE
      RequestParameters:
        method.request.header.Cache-Control: false
        method.request.header.Content-Disposition: false
        method.request.header.Content-Type: false
        method.request.header.ETag: false
      Integration:
        IntegrationHttpMethod: GET
        Type: AWS
        Credentials:
          Fn::GetAtt: [ APIGatewayAWSProxyExecRole, Arn ]
        Uri:
          Fn::Join:
            - '/'
            - - 'arn:aws:apigateway:${opt:region}:s3:path'
              - Ref: SpaBucket
              - 'index.html'
        PassthroughBehavior: WHEN_NO_MATCH
        RequestParameters:
          integration.request.header.Cache-Control: method.request.header.Cache-Control
          integration.request.header.Content-Disposition: method.request.header.Content-Disposition
          integration.request.header.Content-Type: method.request.header.Content-Type
          integration.request.header.ETag: method.request.header.ETag
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Cache-Control: integration.response.header.Cache-Control
              method.response.header.Content-Disposition: integration.response.header.Content-Disposition
              method.response.header.Content-Type: integration.response.header.Content-Type
              method.response.header.ETag: integration.response.header.ETag
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Cache-Control: false
            method.response.header.Content-Disposition: false
            method.response.header.Content-Type: false
            method.response.header.ETag: false

  SpaServerProxyMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: GET
      ResourceId:
        Ref: SpaServerResource
      RestApiId:
        Ref: SpaServer
      AuthorizationType: NONE
      RequestParameters:
        method.request.path.proxy: true
        method.request.header.Cache-Control: false
        method.request.header.Content-Disposition: false
        method.request.header.Content-Type: false
        method.request.header.ETag: false
      Integration:
        Credentials:
          Fn::GetAtt: [ APIGatewayAWSProxyExecRole, Arn ]
        RequestParameters:
          integration.request.path.proxy: method.request.path.proxy
          integration.request.header.Cache-Control: method.request.header.Cache-Control
          integration.request.header.Content-Disposition: method.request.header.Content-Disposition
          integration.request.header.Content-Type: method.request.header.Content-Type
          integration.request.header.ETag: method.request.header.ETag
        IntegrationHttpMethod: GET
        Type: AWS
        Uri:
          Fn::Join:
            - '/'
            - - 'arn:aws:apigateway:${opt:region}:s3:path'
              - Ref: SpaBucket
              - '{proxy}'
        PassthroughBehavior: WHEN_NO_MATCH
        ContentHandling: CONVERT_TO_BINARY
        IntegrationResponses:
          - StatusCode: 200
            SelectionPattern: '-'
            ResponseParameters:
              method.response.header.Cache-Control: integration.response.header.Cache-Control
              method.response.header.Content-Disposition: integration.response.header.Content-Disposition
              method.response.header.Content-Type: integration.response.header.Content-Type
              method.response.header.ETag: integration.response.header.ETag
          - StatusCode: 301
            SelectionPattern: '404'
            ResponseParameters:
              method.response.header.Location: "'${self:custom.apig.redirect, '/${opt:stage}'}'"
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Cache-Control: false
            method.response.header.Content-Disposition: false
            method.response.header.Content-Type: false
            method.response.header.ETag: false
        - StatusCode: 301
          ResponseParameters:
            method.response.header.Location: true

  SpaServerWebACLAssociation:
    Type: AWS::WAFRegional::WebACLAssociation
    Properties:
      ResourceArn:
        Ref: SpaServerDeployment
      WebACLId: ${self:custom.apig.webACLId, 'undefined'}

  SpaServerDomainName:
    Type: AWS::ApiGateway::DomainName
    Properties:
      DomainName: ${self:custom.apig.domainName, 'undefined'}
      RegionalCertificateArn: ${self:custom.apig.acmCertificateArn, 'undefined'}
      SecurityPolicy: TLS_1_2
      EndpointConfiguration:
        Types:
          - REGIONAL
  SpaServerBasePathMapping:
    DependsOn:
      - SpaServer
      - ApiGatewayDeployment
      - SpaServerDomainName
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      DomainName:
        Ref: SpaServerDomainName
      RestApiId:
        Ref: SpaServer
      Stage: ${opt:stage}

  SpaServerEndpointRecord:
    DependsOn:
      - SpaServerDomainName
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: ${self:custom.apig.hostedZoneId, 'undefined'}
      Name:
        Fn::Join:
          - ''
          - - Ref: SpaServerDomainName
            - .
      # Region: ${opt:region}
      # SetIdentifier: ${opt:region}
      # HealthCheckId: ${self:custom.apig.${opt:region}.healthCheckId}
      Type: A
      AliasTarget:
        HostedZoneId:
          Fn::GetAtt:
            - SpaServerDomainName
            - RegionalHostedZoneId
        DNSName:
          Fn::GetAtt:
            - SpaServerDomainName
            - RegionalDomainName

  SpaServerDeployment: # ${sls:instanceId}
    DependsOn:
      - SpaServer
      - SpaServerRootMethod
      - SpaServerProxyMethod
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId:
        Ref: SpaServer
      StageName: ${opt:stage}

Outputs:
  SpaBucketName:
    Value:
      Ref: SpaBucket

  SpaServerId:
    Value:
      Ref: SpaServer

  SpaURL:
    Value: https://${self:custom.apig.domainName, 'undefined'}
